; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; default_envs = spi_test
; default_envs = lcd
; default_envs = voltameter
; default_envs = lvgl
; default_envs = touch
default_envs = wifi_sat
default_envs = factory


lib_dir = ./lib
boards_dir = ./board
src_dir = examples/${platformio.default_envs}

[env]
platform = https://github.com/pioarduino/platform-espressif32.git #develop
board = Lilygo-T-Display-C5
framework = arduino
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
extra_scripts = post:extra_script.py  # find bin file and copy to firmware_bin folder

[env:lvgl]	
[env:voltameter]
[env:spi_test]	
[env:lcd]
[env:wifi_sat]
[env:touch]
[env:factory]
extends = env
build_flags = 
	${env.build_flags}
